spring:
  cloud:
    config:
      server:

  profiles:
     active: native

server:
  port: ${CONFIG_PORT:8888}

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8282/eureka/